In [1]:
import numpy as np

arr1=np.array([1,2,3])

print(arr1)

[1 2 3]


In [3]:
print(arr1.shape)

(3,)


In [4]:
print(type(arr1))

<class 'numpy.ndarray'>


In [5]:
arr1[0]

1

In [7]:
arr1[0]=2
arr1

array([2, 2, 3])

In [11]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr2[1][1]

5

In [14]:
print(arr2.shape)

(2, 3)


In [16]:
arr2[1,1]

5

In [18]:
arr2[-1,-2]

5

In [22]:
arr3=np.array(['a','b','c','d'])
arr3

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [29]:
arrR=np.arange(0,10,1)
arrR

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arrl=np.linspace(0,10,10)
arrl

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [36]:
arrR=np.random.rand(2,2)
arrR

array([[0.54537615, 0.81691504],
       [0.64546429, 0.01383865]])

In [39]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [44]:
print('okay')
print(np.zeros((2,2)))

okay
[[0. 0.]
 [0. 0.]]


In [3]:
import numpy as np
arr=[0,1,2,3,4,5]
print(np.repeat(arr,2))

[0 0 1 1 2 2 3 3 4 4 5 5]


In [4]:
print(np.tile(arr,2))

[0 1 2 3 4 5 0 1 2 3 4 5]


In [5]:
id_mat=np.eye(3)
id_mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [11]:
arr=np.random.rand(3,3)
arr

array([[0.88688451, 0.00221456, 0.99771959],
       [0.21316177, 0.32322543, 0.65782511],
       [0.20477757, 0.41457133, 0.55090225]])

In [12]:
np.diag(arr)

array([0.88688451, 0.32322543, 0.55090225])

In [13]:
arr.ndim

2

In [14]:
arr.size

9

In [16]:
np.random.randint(-5,5,5)

array([-2, -4, -3,  2, -4])

In [21]:
arr+10

array([[10.88688451, 10.00221456, 10.99771959],
       [10.21316177, 10.32322543, 10.65782511],
       [10.20477757, 10.41457133, 10.55090225]])

In [22]:
arr3=np.array([1,2,3,4])
arr3+10

array([11, 12, 13, 14])

In [23]:
np.exp(arr3)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [26]:
np.log2(arr3)

array([0.       , 1.       , 1.5849625, 2.       ])

In [27]:
np.cos(arr3)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [28]:
arr

array([[0.88688451, 0.00221456, 0.99771959],
       [0.21316177, 0.32322543, 0.65782511],
       [0.20477757, 0.41457133, 0.55090225]])

In [29]:
np.sum(arr)

4.251282120357044

In [4]:
import numpy as np
ar=np.random.rand(5,5)
ar

array([[0.5154914 , 0.06265941, 0.16254825, 0.67595077, 0.78055443],
       [0.77070489, 0.27251174, 0.61687351, 0.10579729, 0.44760595],
       [0.42592328, 0.72985356, 0.60222534, 0.47875941, 0.40300076],
       [0.68473501, 0.06208199, 0.52917485, 0.54140097, 0.30023779],
       [0.60787384, 0.51075457, 0.65730005, 0.53334991, 0.77459633]])

In [12]:
ar[1:4]

array([[0.77070489, 0.27251174, 0.61687351, 0.10579729],
       [0.42592328, 0.72985356, 0.60222534, 0.47875941],
       [0.68473501, 0.06208199, 0.52917485, 0.54140097],
       [0.60787384, 0.51075457, 0.65730005, 0.53334991]])

In [14]:
np.sort(ar,axis=1)

array([[0.06265941, 0.16254825, 0.5154914 , 0.67595077, 0.78055443],
       [0.10579729, 0.27251174, 0.44760595, 0.61687351, 0.77070489],
       [0.40300076, 0.42592328, 0.47875941, 0.60222534, 0.72985356],
       [0.06208199, 0.30023779, 0.52917485, 0.54140097, 0.68473501],
       [0.51075457, 0.53334991, 0.60787384, 0.65730005, 0.77459633]])

In [15]:
np.sort(ar,axis=0)

array([[0.42592328, 0.06208199, 0.16254825, 0.10579729, 0.30023779],
       [0.5154914 , 0.06265941, 0.52917485, 0.47875941, 0.40300076],
       [0.60787384, 0.27251174, 0.60222534, 0.53334991, 0.44760595],
       [0.68473501, 0.51075457, 0.61687351, 0.54140097, 0.77459633],
       [0.77070489, 0.72985356, 0.65730005, 0.67595077, 0.78055443]])

In [22]:
ar


array([[0.5154914 , 0.06265941, 0.16254825, 0.67595077, 0.78055443],
       [0.77070489, 0.27251174, 0.61687351, 0.10579729, 0.44760595],
       [0.42592328, 0.72985356, 0.60222534, 0.47875941, 0.40300076],
       [0.68473501, 0.06208199, 0.52917485, 0.54140097, 0.30023779],
       [0.60787384, 0.51075457, 0.65730005, 0.53334991, 0.77459633]])

In [31]:
ar[:3,:3]

array([[0.5154914 , 0.06265941, 0.16254825],
       [0.77070489, 0.27251174, 0.61687351],
       [0.42592328, 0.72985356, 0.60222534]])

In [34]:
ar[:3,:3].T


array([[0.5154914 , 0.77070489, 0.42592328],
       [0.06265941, 0.27251174, 0.72985356],
       [0.16254825, 0.61687351, 0.60222534]])

In [36]:
ar.flatten()

array([0.5154914 , 0.06265941, 0.16254825, 0.67595077, 0.78055443,
       0.77070489, 0.27251174, 0.61687351, 0.10579729, 0.44760595,
       0.42592328, 0.72985356, 0.60222534, 0.47875941, 0.40300076,
       0.68473501, 0.06208199, 0.52917485, 0.54140097, 0.30023779,
       0.60787384, 0.51075457, 0.65730005, 0.53334991, 0.77459633])

In [37]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [49]:
arr1=np.append(arr,4)
arr1

array([1, 2, 3, 4])

In [50]:
arr2=np.insert(arr1,0,[-1,0])
arr2

array([-1,  0,  1,  2,  3,  4])

In [45]:
arr3=np.delete(arr2,[0,1,5])
arr3

array([1, 2, 3])

In [56]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr2=np.array([[9,10,11,12],[13,14,15,16]])
arr3=np.concatenate((arr1,arr2),axis=1)
arr3

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

In [54]:
arr4=np.hstack((arr1,arr2))
arr4

array([[ 1,  2,  3,  4,  9, 10, 11, 12, 15],
       [ 5,  6,  7,  8, 13, 14, 15, 16, 17]])

In [58]:
arr5=np.vstack((arr1,arr2))
arr5

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [59]:
arr=np.array([1,2,3,4,5,4,3,2,1,3,4,7])
np.unique(arr)

array([1, 2, 3, 4, 5, 7])

In [62]:
uniques,counts=np.unique(arr,return_counts=True)
print(uniques)
print(counts)

[1 2 3 4 5 7]
[2 2 3 3 1 1]


In [72]:
arr1=np.array([1,2,3,4])
arr2=np.array([4,3,6,7])
print(np.intersect1d(arr1,arr2))
print(np.union1d(arr1,arr2))
print(np.setdiff1d(arr2,arr1))
print(np.setxor1d(arr2,arr1))

[3 4]
[1 2 3 4 6 7]
[6 7]
[1 2 6 7]
